version: 2

references:

  - &docker_container
    docker:
      - image: docker
    working_directory: ~/project

jobs:

  build_docker:
    <<: *docker_container
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build application Docker image
          command: |
            docker build -t nippos .

  test:
    <<: *docker_container
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build application Docker image
          command: |
            docker run \
              -e PARAGRAPH_JSON \
              -e SLACK_TOKEN \
              -e SLACK_DOMAIN \
              -e SLACK_USER_ID \
              -e SLACK_CHANNEL_ID \
              -e SLACK_CHANNEL_TYPE \
              -e SLACK_CHANNEL_TYPE \
              -e QIITA_TOKEN \
              -e QIITA_DOMAIN \
              -e QIITA_TITLE \
              -e QIITA_TAGS \
              -it nippos sh -c 'hh2md | postm' > /dev/null

workflows:
  version: 2

  commit:
    jobs:
      - build_docker
      - test:
          requires:
            - build_docker
