version: 2

references:

  - &docker_container
    docker:
      - image: docker
    working_directory: ~/project

  - &build_image
    run:
      name: Build docker image
      command: |
        docker build -t nippos .

jobs:

  build_docker:
    <<: *docker_container
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - *build_image

  post_if_clockout:
    <<: *docker_container
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - *build_image
      - run:
          name: Check clockout from slack
          command: |
            docker run \
              -e TZ \
              -e SLACK_TOKEN \
              -e SLACK_DOMAIN \
              -e SLACK_USER_ID \
              -e SLACK_CHANNEL_ID \
              -e SLACK_CHANNEL_TYPE \
              -it nippos sh -c '! clockout --date 2018-07-04'
      - run:
          name: Post qiita from slack
          command: |
            docker run \
              -e TZ \
              -e PARAGRAPH_JSON \
              -e SLACK_TOKEN \
              -e SLACK_DOMAIN \
              -e SLACK_USER_ID \
              -e SLACK_CHANNEL_ID \
              -e SLACK_CHANNEL_TYPE \
              -e QIITA_TOKEN \
              -e QIITA_DOMAIN \
              -e QIITA_TITLE \
              -e QIITA_TAGS \
              -it nippos sh -c 'hh2md --date 2018-07-04 | postm' > /dev/null
          when: on_fail

workflows:
  version: 2

  push:
    jobs:
      - build_docker

  polling:
    triggers:
      - schedule:
          cron: "5,10,15,20,25,30,35,40,45,50,55 * * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - post_if_clockout
