version: 2

references:

  - &docker_container
    docker:
      - image: docker
    working_directory: ~/project

jobs:

  build_docker:
    <<: *docker_container
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build docker image
          command: |
            docker build -t nippos .
      - run:
          name: Cache docker images
          command: |
            mkdir -p ~/caches
            docker save $(docker images -q) -o ~/caches/images.tar
            docker images
      - save_cache:
          key: docker-{{ checksum ".dockerignore" }}-{{ checksum "Dockerfile" }}
          paths: ~/caches/images.tar

  test:
    <<: *docker_container
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - restore_cache:
          key: docker-{{ checksum ".dockerignore" }}-{{ checksum "Dockerfile" }}
          paths: ~/caches/images.tar
      - run:
          name: Load docker images
          command: |
            set +o pipefail
            docker load -i ~/caches/images.tar | true
            docker images
      - run:
          name: Build application Docker image
          command: |
            docker run \
              -e PARAGRAPH_JSON \
              -e SLACK_TOKEN \
              -e SLACK_DOMAIN \
              -e SLACK_USER_ID \
              -e SLACK_CHANNEL_ID \
              -e SLACK_CHANNEL_TYPE \
              -e SLACK_CHANNEL_TYPE \
              -e QIITA_TOKEN \
              -e QIITA_DOMAIN \
              -e QIITA_TITLE \
              -e QIITA_TAGS \
              -it nippos sh -c 'hh2md | postm' > /dev/null

workflows:
  version: 2

  commit:
    jobs:
      - build_docker
      - test:
          requires:
            - build_docker
